// For reminds reducer

export const SET_REMINDS_ARRAY = "SET_REMINDS_ARRAY";
export const CHANGE_REMINDS_ITEM = "CHANGE_REMINDS_ITEM";
export const REMOVE_REMINDS_ITEM = "REMOVE_REMINDS_ITEM";
export const SET_CURRENT_REMINDS_PAGE = "SET_CURRENT_REMINDS_PAGE";
export const ADD_REMINDS_ITEM = "ADD_REMINDS_ITEM";
export const SET_DEADLINE_ARRAY = "SET_DEADLINE_ARRAY";

// For targets reducer

export const SET_TARGETS_ARRAY = "SET_TARGETS_ARRAY";
export const SET_TARGETS_PAGES = "SET_TARGETS_PAGES";
export const SET_COMPLETED_TARGETS = "SET_COMPLETED_TARGETS";
export const SET_CURRENT_TARGETS_PAGE = "SET_CURRENT_TARGETS_PAGE";
export const ADD_TARGET_ITEM = "ADD_TARGET_ITEM";
export const REMOVE_TARGET_ITEM = "REMOVE_TARGET_ITEM";
export const CHANGE_TARGETS_ITEM = "CHANGE_TARGETS_ITEM";
export const CHANGE_TARGETS_ITEM_STATUS = "CHANGE_TARGETS_ITEM_STATUS";

// user

export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const CHECK_USER_AUTH = "CHECK_USER_AUTH";
