// For reminds reducer

export const SET_REMINDS_ARRAY = "SET_REMINDS_ARRAY";
export const CHANGE_REMINDS_ITEM = "CHANGE_REMINDS_ITEM";
export const REMOVE_REMINDS_ITEM = "REMOVE_REMINDS_ITEM";
export const ADD_REMINDS_ITEM = "ADD_REMINDS_ITEM";
export const SET_DEADLINE_ARRAY = "SET_DEADLINE_ARRAY";

// For targets reducer

export const SET_TARGETS_ARRAY = "SET_TARGETS_ARRAY";
export const ADD_TARGET_ITEM = "ADD_TARGET_ITEM";
export const REMOVE_TARGET_ITEM = "REMOVE_TARGET_ITEM";
export const CHANGE_TARGETS_ITEM = "CHANGE_TARGETS_ITEM";
export const CHANGE_TARGETS_ITEM_STATUS = "CHANGE_TARGETS_ITEM_STATUS";
